import { TBenevityCSVParser, TBenevityDonation } from '../benevity.types'

export const benevityInitialValues: TBenevityCSVParser = {
  charityId: '',
  charityName: '',
  currency: '',
  donations: [],
  periodEnding: '',
  paymentMethod: '',
  disbursementId: '',
  checkFee: '',
  totalDonationsGross: '',
  netTotalPayment: 0,
  transactionAmount: 0,
  exchangeRate: 0,
  note: '',
}

export const benevityDonationInitialValues: TBenevityDonation = {
  company: '',
  project: '',
  donationDate: '',
  donorFirstName: '',
  donorLastName: '',
  email: '',
  address: '',
  city: '',
  stateProvince: '',
  postalCode: '',
  activity: '',
  comment: '',
  transactionId: '',
  donationFrequency: '',
  currency: '',
  projectRemoteId: '',
  source: '',
  reason: '',
  totalDonationToBeAcknowledged: 0,
  matchAmount: 0,
  causeSupportFee: 0,
  merchantFee: 0,
  feeComment: '',
  totalFee: 0,
  totalAmount: 0,
}
