apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      containers:
        - name: frontend
          resources:
            limits:
              memory: 400Mi
              cpu: 800m
          env:
            - name: "API_URL"
              value: "https://podkrepi.bg/api/v1"
            - name: "APP_URL"
              value: "https://podkrepi.bg"
