
CREATE DATABASE app;
-- POSTGRESQL does not support CREATE IF NOT EXISTS, it needs to be faked
-- CREATE USER IF NOT EXISTS %s WITH PASSWORD NULL;
-- CREATE USER IF NOT EXISTS %s WITH PASSWORD '%s';
-- GRANT ALL ON DATABASE %s TO %s;
-- GRANT admin TO %s;

