BEGIN;

-- SCHEMAS WILL BE CREATED INSIDE OF THE CURRENTLY UED DATABASE;
CREATE SCHEMA IF NOT EXISTS "app";
CREATE SCHEMA IF NOT EXISTS "campaign";
CREATE SCHEMA IF NOT EXISTS "util";

-- DROP THE DEFAULT SCHEMA IF IT EXISTS
DROP SCHEMA IF EXISTS "public";

COMMIT;
