// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDetails struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDetails) Reset()         { *m = ErrorDetails{} }
func (m *ErrorDetails) String() string { return proto.CompactTextString(m) }
func (*ErrorDetails) ProtoMessage()    {}
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{0}
}

func (m *ErrorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetails.Unmarshal(m, b)
}
func (m *ErrorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetails.Marshal(b, m, deterministic)
}
func (m *ErrorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetails.Merge(m, src)
}
func (m *ErrorDetails) XXX_Size() int {
	return xxx_messageInfo_ErrorDetails.Size(m)
}
func (m *ErrorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetails proto.InternalMessageInfo

func (m *ErrorDetails) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ErrorDetails) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Error struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Domain               string          `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Message              string          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Trace                string          `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	Details              []*ErrorDetails `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetTrace() string {
	if m != nil {
		return m.Trace
	}
	return ""
}

func (m *Error) GetDetails() []*ErrorDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorDetails)(nil), "podkrepibg.ErrorDetails")
	proto.RegisterType((*Error)(nil), "podkrepibg.Error")
}

func init() { proto.RegisterFile("errors.proto", fileDescriptor_24fe73c7f0ddb19c) }

var fileDescriptor_24fe73c7f0ddb19c = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x4f, 0xb1, 0x0e, 0x82, 0x30,
	0x14, 0x0c, 0x42, 0x41, 0x9f, 0x0c, 0xe6, 0xc5, 0x98, 0x8e, 0x84, 0x89, 0x89, 0x01, 0x37, 0x47,
	0xa3, 0x3f, 0xc0, 0xe8, 0x56, 0xe8, 0x0b, 0x21, 0x88, 0x25, 0x2d, 0x8b, 0x5f, 0xe2, 0xef, 0x1a,
	0x5a, 0x88, 0xb8, 0xdd, 0xdd, 0x7b, 0x77, 0xb9, 0x83, 0x98, 0xb4, 0x56, 0xda, 0xe4, 0x83, 0x56,
	0xa3, 0x42, 0x18, 0x94, 0xec, 0x34, 0x0d, 0x6d, 0xd5, 0xa4, 0x17, 0x88, 0xef, 0xd3, 0xed, 0x46,
	0xa3, 0x68, 0x9f, 0x06, 0x0f, 0xe0, 0x77, 0xf4, 0xe6, 0x5e, 0xe2, 0x65, 0xbb, 0x72, 0x82, 0xc8,
	0x21, 0xea, 0xc9, 0x18, 0xd1, 0x10, 0xdf, 0x58, 0x75, 0xa1, 0xe9, 0xc7, 0x03, 0x66, 0xcd, 0x88,
	0x10, 0xd4, 0x4a, 0x92, 0xb5, 0xb1, 0xd2, 0x62, 0x3c, 0x41, 0x28, 0x55, 0x2f, 0xda, 0xd7, 0x6c,
	0x9b, 0xd9, 0x3a, 0xcf, 0xff, 0xcb, 0xc3, 0x23, 0xb0, 0x51, 0x8b, 0x9a, 0x78, 0x60, 0x75, 0x47,
	0xb0, 0x80, 0x48, 0xba, 0x72, 0x9c, 0x25, 0x7e, 0xb6, 0x2f, 0x78, 0xfe, 0xeb, 0x9f, 0xaf, 0xcb,
	0x97, 0xcb, 0xe3, 0x75, 0xfb, 0x08, 0xdd, 0xe2, 0x2a, 0xb4, 0x93, 0xcf, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1b, 0xa6, 0xa0, 0xd0, 0x02, 0x01, 0x00, 0x00,
}
