BEGIN;

CREATE DATABASE IF NOT EXISTS app;
-- CREATE USER IF NOT EXISTS %s WITH PASSWORD NULL;
-- CREATE USER IF NOT EXISTS %s WITH PASSWORD '%s';
-- GRANT ALL ON DATABASE %s TO %s;
-- GRANT admin TO %s;

COMMIT;
