export const data: any = [
  {
    id: '1',
    type: 'star',
    taskName: 'Да помогнем на Радост да проходи',
    keyword: 'Договори',
    description: 'Експериментално лечение',
    status: '50%',
    deadline: 'остават 7 дни',
    operator: 'Ivan',
  },
  {
    id: '2',
    taskName: 'Да помогнем на Радост да проходи',
    keyword: 'Договори',
    description: 'Експериментално лечение',
    status: '50%',
    deadline: 'остават 7 дни',
    operator: 'Ivan',
  },
  {
    id: '3',
    taskName: 'Да помогнем на Радост да проходи',
    keyword: 'Договори',
    description: 'Експериментално лечение',
    status: '50%',
    deadline: 'остават 7 дни',
    operator: 'Ivan',
  },
  {
    id: '4',
    taskName: 'Да помогнем на Радост да проходи',
    keyword: 'Договори',
    description: 'Експериментално лечение',
    status: '50%',
    deadline: 'остават 7 дни',
    operator: 'Ivan',
  },
  {
    id: '5',
    taskName: 'Да помогнем на Радост да проходи',
    keyword: 'Договори',
    description: 'Експериментално лечение',
    status: '50%',
    deadline: 'остават 7 дни',
    operator: 'Ivan',
  },
]
