// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaigns.proto

package campaigns

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCampaignRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizerId          string   `protobuf:"bytes,2,opt,name=organizerId,proto3" json:"organizerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignRequest) Reset()         { *m = CreateCampaignRequest{} }
func (m *CreateCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignRequest) ProtoMessage()    {}
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ca6c0cb2a0d76f, []int{0}
}

func (m *CreateCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignRequest.Unmarshal(m, b)
}
func (m *CreateCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignRequest.Marshal(b, m, deterministic)
}
func (m *CreateCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignRequest.Merge(m, src)
}
func (m *CreateCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignRequest.Size(m)
}
func (m *CreateCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignRequest proto.InternalMessageInfo

func (m *CreateCampaignRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCampaignRequest) GetOrganizerId() string {
	if m != nil {
		return m.OrganizerId
	}
	return ""
}

type CreateCampaignResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignResponse) Reset()         { *m = CreateCampaignResponse{} }
func (m *CreateCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignResponse) ProtoMessage()    {}
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ca6c0cb2a0d76f, []int{1}
}

func (m *CreateCampaignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignResponse.Unmarshal(m, b)
}
func (m *CreateCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignResponse.Marshal(b, m, deterministic)
}
func (m *CreateCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignResponse.Merge(m, src)
}
func (m *CreateCampaignResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignResponse.Size(m)
}
func (m *CreateCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignResponse proto.InternalMessageInfo

func (m *CreateCampaignResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateCampaignResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCampaignResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateCampaignResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCampaignRequest)(nil), "podkrepibg.CreateCampaignRequest")
	proto.RegisterType((*CreateCampaignResponse)(nil), "podkrepibg.CreateCampaignResponse")
}

func init() { proto.RegisterFile("campaigns.proto", fileDescriptor_c5ca6c0cb2a0d76f) }

var fileDescriptor_c5ca6c0cb2a0d76f = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4e, 0xcc, 0x2d,
	0x48, 0xcc, 0x4c, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0xc8, 0x4f,
	0xc9, 0x2e, 0x4a, 0x2d, 0xc8, 0x4c, 0x4a, 0x57, 0xf2, 0xe5, 0x12, 0x75, 0x2e, 0x4a, 0x4d, 0x2c,
	0x49, 0x75, 0x86, 0x2a, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x14, 0xb8, 0xb8,
	0xf3, 0x8b, 0xd2, 0x13, 0xf3, 0x32, 0xab, 0x52, 0x8b, 0x3c, 0x53, 0x24, 0x98, 0xc0, 0x52, 0xc8,
	0x42, 0x4a, 0x75, 0x5c, 0x62, 0xe8, 0xc6, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xf1, 0x71,
	0x31, 0x65, 0xa6, 0x40, 0x4d, 0x63, 0xca, 0x4c, 0x81, 0x9b, 0xcf, 0x84, 0x64, 0xbe, 0x0c, 0x17,
	0x67, 0x6a, 0x51, 0x51, 0x7e, 0x91, 0x73, 0x7e, 0x4a, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b,
	0x10, 0x42, 0x40, 0x48, 0x89, 0x8b, 0x07, 0xcc, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95,
	0x60, 0x01, 0xeb, 0x44, 0x11, 0x33, 0x4a, 0xe1, 0xe2, 0x84, 0xd9, 0x5c, 0x2c, 0x14, 0xce, 0xc5,
	0x87, 0xea, 0x18, 0x21, 0x45, 0x3d, 0x84, 0xd7, 0xf5, 0xb0, 0xfa, 0x5b, 0x4a, 0x09, 0x9f, 0x12,
	0x88, 0x5f, 0x9c, 0x94, 0xa2, 0x38, 0xe1, 0x61, 0xba, 0x8a, 0x49, 0x24, 0x00, 0x49, 0x03, 0x4c,
	0x38, 0x89, 0x0d, 0x1c, 0xd6, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xbd, 0xaa, 0x4f,
	0x7e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampaignsClient is the client API for Campaigns service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampaignsClient interface {
	// creates a new campaign
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error)
}

type campaignsClient struct {
	cc *grpc.ClientConn
}

func NewCampaignsClient(cc *grpc.ClientConn) CampaignsClient {
	return &campaignsClient{cc}
}

func (c *campaignsClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error) {
	out := new(CreateCampaignResponse)
	err := c.cc.Invoke(ctx, "/podkrepibg.Campaigns/CreateCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignsServer is the server API for Campaigns service.
type CampaignsServer interface {
	// creates a new campaign
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error)
}

// UnimplementedCampaignsServer can be embedded to have forward compatible implementations.
type UnimplementedCampaignsServer struct {
}

func (*UnimplementedCampaignsServer) CreateCampaign(ctx context.Context, req *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}

func RegisterCampaignsServer(s *grpc.Server, srv CampaignsServer) {
	s.RegisterService(&_Campaigns_serviceDesc, srv)
}

func _Campaigns_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podkrepibg.Campaigns/CreateCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Campaigns_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podkrepibg.Campaigns",
	HandlerType: (*CampaignsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _Campaigns_CreateCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaigns.proto",
}
