// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaign.proto

package campaign

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCampaignRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizerId          string   `protobuf:"bytes,2,opt,name=organizerId,proto3" json:"organizerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignRequest) Reset()         { *m = CreateCampaignRequest{} }
func (m *CreateCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignRequest) ProtoMessage()    {}
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{0}
}

func (m *CreateCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignRequest.Unmarshal(m, b)
}
func (m *CreateCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignRequest.Marshal(b, m, deterministic)
}
func (m *CreateCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignRequest.Merge(m, src)
}
func (m *CreateCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignRequest.Size(m)
}
func (m *CreateCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignRequest proto.InternalMessageInfo

func (m *CreateCampaignRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCampaignRequest) GetOrganizerId() string {
	if m != nil {
		return m.OrganizerId
	}
	return ""
}

type CreateCampaignResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignResponse) Reset()         { *m = CreateCampaignResponse{} }
func (m *CreateCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignResponse) ProtoMessage()    {}
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{1}
}

func (m *CreateCampaignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignResponse.Unmarshal(m, b)
}
func (m *CreateCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignResponse.Marshal(b, m, deterministic)
}
func (m *CreateCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignResponse.Merge(m, src)
}
func (m *CreateCampaignResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignResponse.Size(m)
}
func (m *CreateCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignResponse proto.InternalMessageInfo

func (m *CreateCampaignResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateCampaignResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCampaignResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateCampaignResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCampaignRequest)(nil), "podkrepibg.campaign.CreateCampaignRequest")
	proto.RegisterType((*CreateCampaignResponse)(nil), "podkrepibg.campaign.CreateCampaignResponse")
}

func init() { proto.RegisterFile("campaign.proto", fileDescriptor_dce769fb84410dc2) }

var fileDescriptor_dce769fb84410dc2 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4e, 0xcc, 0x2d,
	0x48, 0xcc, 0x4c, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0xc8, 0x4f, 0xc9,
	0x2e, 0x4a, 0x2d, 0xc8, 0x4c, 0x4a, 0xd7, 0x83, 0x49, 0x29, 0xf9, 0x72, 0x89, 0x3a, 0x17, 0xa5,
	0x26, 0x96, 0xa4, 0x3a, 0x43, 0x45, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x05,
	0x2e, 0xee, 0xfc, 0xa2, 0xf4, 0xc4, 0xbc, 0xcc, 0xaa, 0xd4, 0x22, 0xcf, 0x14, 0x09, 0x26, 0xb0,
	0x14, 0xb2, 0x90, 0x52, 0x1d, 0x97, 0x18, 0xba, 0x71, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x50, 0xd3, 0x98, 0x32, 0x53, 0xe0, 0xe6, 0x33, 0x21, 0x99, 0x2f,
	0xc3, 0xc5, 0x99, 0x5a, 0x54, 0x94, 0x5f, 0xe4, 0x9c, 0x9f, 0x92, 0x2a, 0xc1, 0xac, 0xc0, 0xa8,
	0xc1, 0x1a, 0x84, 0x10, 0x10, 0x52, 0xe2, 0xe2, 0x01, 0x73, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3,
	0x53, 0x25, 0x58, 0xc0, 0x3a, 0x51, 0xc4, 0x8c, 0x6a, 0xb8, 0xf8, 0x61, 0x36, 0x07, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x0a, 0x65, 0x72, 0xf1, 0xa1, 0x3a, 0x49, 0x48, 0x4b, 0x0f, 0x4b, 0x48,
	0xe8, 0x61, 0x0d, 0x06, 0x29, 0x6d, 0xa2, 0xd4, 0x42, 0xfc, 0xe8, 0xa4, 0x18, 0xc5, 0x01, 0x53,
	0xb2, 0x8a, 0x49, 0x24, 0x00, 0xa1, 0x11, 0xa6, 0xb2, 0x38, 0x89, 0x0d, 0x1c, 0x17, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x6c, 0x31, 0x2c, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampaignServiceClient is the client API for CampaignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampaignServiceClient interface {
	// creates a new campaign
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error)
}

type campaignServiceClient struct {
	cc *grpc.ClientConn
}

func NewCampaignServiceClient(cc *grpc.ClientConn) CampaignServiceClient {
	return &campaignServiceClient{cc}
}

func (c *campaignServiceClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error) {
	out := new(CreateCampaignResponse)
	err := c.cc.Invoke(ctx, "/podkrepibg.campaign.CampaignService/CreateCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignServiceServer is the server API for CampaignService service.
type CampaignServiceServer interface {
	// creates a new campaign
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error)
}

// UnimplementedCampaignServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCampaignServiceServer struct {
}

func (*UnimplementedCampaignServiceServer) CreateCampaign(ctx context.Context, req *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}

func RegisterCampaignServiceServer(s *grpc.Server, srv CampaignServiceServer) {
	s.RegisterService(&_CampaignService_serviceDesc, srv)
}

func _CampaignService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podkrepibg.campaign.CampaignService/CreateCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CampaignService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podkrepibg.campaign.CampaignService",
	HandlerType: (*CampaignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _CampaignService_CreateCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaign.proto",
}
