// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaign.proto

package campaign

import (
	common "common"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCampaignRequest struct {
	InitiatorId          string   `protobuf:"bytes,1,opt,name=initiatorId,proto3" json:"initiatorId,omitempty"`
	OperatorId           string   `protobuf:"bytes,2,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	BeneficiaryId        string   `protobuf:"bytes,3,opt,name=beneficiaryId,proto3" json:"beneficiaryId,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCampaignRequest) Reset()         { *m = CreateCampaignRequest{} }
func (m *CreateCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignRequest) ProtoMessage()    {}
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{0}
}

func (m *CreateCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignRequest.Unmarshal(m, b)
}
func (m *CreateCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignRequest.Marshal(b, m, deterministic)
}
func (m *CreateCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignRequest.Merge(m, src)
}
func (m *CreateCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignRequest.Size(m)
}
func (m *CreateCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignRequest proto.InternalMessageInfo

func (m *CreateCampaignRequest) GetInitiatorId() string {
	if m != nil {
		return m.InitiatorId
	}
	return ""
}

func (m *CreateCampaignRequest) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *CreateCampaignRequest) GetBeneficiaryId() string {
	if m != nil {
		return m.BeneficiaryId
	}
	return ""
}

func (m *CreateCampaignRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings.
type CreateCampaignResponse struct {
	CampaignId           string               `protobuf:"bytes,1,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InitiatorId          string               `protobuf:"bytes,3,opt,name=initiatorId,proto3" json:"initiatorId,omitempty"`
	OperatorId           string               `protobuf:"bytes,4,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	BeneficiaryId        string               `protobuf:"bytes,5,opt,name=beneficiaryId,proto3" json:"beneficiaryId,omitempty"`
	State                common.CampaignState `protobuf:"varint,6,opt,name=state,proto3,enum=podkrepibg.common.nomenclatures.CampaignState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateCampaignResponse) Reset()         { *m = CreateCampaignResponse{} }
func (m *CreateCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCampaignResponse) ProtoMessage()    {}
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{1}
}

func (m *CreateCampaignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCampaignResponse.Unmarshal(m, b)
}
func (m *CreateCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCampaignResponse.Marshal(b, m, deterministic)
}
func (m *CreateCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCampaignResponse.Merge(m, src)
}
func (m *CreateCampaignResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCampaignResponse.Size(m)
}
func (m *CreateCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCampaignResponse proto.InternalMessageInfo

func (m *CreateCampaignResponse) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *CreateCampaignResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCampaignResponse) GetInitiatorId() string {
	if m != nil {
		return m.InitiatorId
	}
	return ""
}

func (m *CreateCampaignResponse) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *CreateCampaignResponse) GetBeneficiaryId() string {
	if m != nil {
		return m.BeneficiaryId
	}
	return ""
}

func (m *CreateCampaignResponse) GetState() common.CampaignState {
	if m != nil {
		return m.State
	}
	return common.CampaignState_UndefinedCampaign
}

type CampaignTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignTypesRequest) Reset()         { *m = CampaignTypesRequest{} }
func (m *CampaignTypesRequest) String() string { return proto.CompactTextString(m) }
func (*CampaignTypesRequest) ProtoMessage()    {}
func (*CampaignTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{2}
}

func (m *CampaignTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignTypesRequest.Unmarshal(m, b)
}
func (m *CampaignTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignTypesRequest.Marshal(b, m, deterministic)
}
func (m *CampaignTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignTypesRequest.Merge(m, src)
}
func (m *CampaignTypesRequest) XXX_Size() int {
	return xxx_messageInfo_CampaignTypesRequest.Size(m)
}
func (m *CampaignTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignTypesRequest proto.InternalMessageInfo

type CampaignTypesReply struct {
	CampaignTypes        []*CampaignType `protobuf:"bytes,1,rep,name=campaignTypes,proto3" json:"campaignTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CampaignTypesReply) Reset()         { *m = CampaignTypesReply{} }
func (m *CampaignTypesReply) String() string { return proto.CompactTextString(m) }
func (*CampaignTypesReply) ProtoMessage()    {}
func (*CampaignTypesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{3}
}

func (m *CampaignTypesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignTypesReply.Unmarshal(m, b)
}
func (m *CampaignTypesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignTypesReply.Marshal(b, m, deterministic)
}
func (m *CampaignTypesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignTypesReply.Merge(m, src)
}
func (m *CampaignTypesReply) XXX_Size() int {
	return xxx_messageInfo_CampaignTypesReply.Size(m)
}
func (m *CampaignTypesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignTypesReply.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignTypesReply proto.InternalMessageInfo

func (m *CampaignTypesReply) GetCampaignTypes() []*CampaignType {
	if m != nil {
		return m.CampaignTypes
	}
	return nil
}

type CampaignType struct {
	CampaignTypeId       string             `protobuf:"bytes,1,opt,name=campaignTypeId,proto3" json:"campaignTypeId,omitempty"`
	CampaignTypeName     string             `protobuf:"bytes,2,opt,name=campaignTypeName,proto3" json:"campaignTypeName,omitempty"`
	CampaignTypeDescr    string             `protobuf:"bytes,3,opt,name=campaignTypeDescr,proto3" json:"campaignTypeDescr,omitempty"`
	SubTypes             []*CampaignSubType `protobuf:"bytes,4,rep,name=subTypes,proto3" json:"subTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CampaignType) Reset()         { *m = CampaignType{} }
func (m *CampaignType) String() string { return proto.CompactTextString(m) }
func (*CampaignType) ProtoMessage()    {}
func (*CampaignType) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{4}
}

func (m *CampaignType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignType.Unmarshal(m, b)
}
func (m *CampaignType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignType.Marshal(b, m, deterministic)
}
func (m *CampaignType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignType.Merge(m, src)
}
func (m *CampaignType) XXX_Size() int {
	return xxx_messageInfo_CampaignType.Size(m)
}
func (m *CampaignType) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignType.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignType proto.InternalMessageInfo

func (m *CampaignType) GetCampaignTypeId() string {
	if m != nil {
		return m.CampaignTypeId
	}
	return ""
}

func (m *CampaignType) GetCampaignTypeName() string {
	if m != nil {
		return m.CampaignTypeName
	}
	return ""
}

func (m *CampaignType) GetCampaignTypeDescr() string {
	if m != nil {
		return m.CampaignTypeDescr
	}
	return ""
}

func (m *CampaignType) GetSubTypes() []*CampaignSubType {
	if m != nil {
		return m.SubTypes
	}
	return nil
}

type CampaignSubType struct {
	CampaignSubTypeId    string   `protobuf:"bytes,1,opt,name=campaignSubTypeId,proto3" json:"campaignSubTypeId,omitempty"`
	CampaignSubTypeName  string   `protobuf:"bytes,2,opt,name=campaignSubTypeName,proto3" json:"campaignSubTypeName,omitempty"`
	CampaignSubTypeDescr string   `protobuf:"bytes,3,opt,name=campaignSubTypeDescr,proto3" json:"campaignSubTypeDescr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignSubType) Reset()         { *m = CampaignSubType{} }
func (m *CampaignSubType) String() string { return proto.CompactTextString(m) }
func (*CampaignSubType) ProtoMessage()    {}
func (*CampaignSubType) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{5}
}

func (m *CampaignSubType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignSubType.Unmarshal(m, b)
}
func (m *CampaignSubType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignSubType.Marshal(b, m, deterministic)
}
func (m *CampaignSubType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignSubType.Merge(m, src)
}
func (m *CampaignSubType) XXX_Size() int {
	return xxx_messageInfo_CampaignSubType.Size(m)
}
func (m *CampaignSubType) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignSubType.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignSubType proto.InternalMessageInfo

func (m *CampaignSubType) GetCampaignSubTypeId() string {
	if m != nil {
		return m.CampaignSubTypeId
	}
	return ""
}

func (m *CampaignSubType) GetCampaignSubTypeName() string {
	if m != nil {
		return m.CampaignSubTypeName
	}
	return ""
}

func (m *CampaignSubType) GetCampaignSubTypeDescr() string {
	if m != nil {
		return m.CampaignSubTypeDescr
	}
	return ""
}

type FilterCampaignsRequest struct {
	CampaignTypes        *CampaignType        `protobuf:"bytes,1,opt,name=campaignTypes,proto3" json:"campaignTypes,omitempty"`
	CampaignSubTypes     *CampaignSubType     `protobuf:"bytes,2,opt,name=campaignSubTypes,proto3" json:"campaignSubTypes,omitempty"`
	State                common.CampaignState `protobuf:"varint,3,opt,name=state,proto3,enum=podkrepibg.common.nomenclatures.CampaignState" json:"state,omitempty"`
	OperatorId           string               `protobuf:"bytes,4,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	InitiatorId          string               `protobuf:"bytes,5,opt,name=initiatorId,proto3" json:"initiatorId,omitempty"`
	BeneficiaryId        string               `protobuf:"bytes,6,opt,name=beneficiaryId,proto3" json:"beneficiaryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FilterCampaignsRequest) Reset()         { *m = FilterCampaignsRequest{} }
func (m *FilterCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*FilterCampaignsRequest) ProtoMessage()    {}
func (*FilterCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{6}
}

func (m *FilterCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterCampaignsRequest.Unmarshal(m, b)
}
func (m *FilterCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterCampaignsRequest.Marshal(b, m, deterministic)
}
func (m *FilterCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterCampaignsRequest.Merge(m, src)
}
func (m *FilterCampaignsRequest) XXX_Size() int {
	return xxx_messageInfo_FilterCampaignsRequest.Size(m)
}
func (m *FilterCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterCampaignsRequest proto.InternalMessageInfo

func (m *FilterCampaignsRequest) GetCampaignTypes() *CampaignType {
	if m != nil {
		return m.CampaignTypes
	}
	return nil
}

func (m *FilterCampaignsRequest) GetCampaignSubTypes() *CampaignSubType {
	if m != nil {
		return m.CampaignSubTypes
	}
	return nil
}

func (m *FilterCampaignsRequest) GetState() common.CampaignState {
	if m != nil {
		return m.State
	}
	return common.CampaignState_UndefinedCampaign
}

func (m *FilterCampaignsRequest) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *FilterCampaignsRequest) GetInitiatorId() string {
	if m != nil {
		return m.InitiatorId
	}
	return ""
}

func (m *FilterCampaignsRequest) GetBeneficiaryId() string {
	if m != nil {
		return m.BeneficiaryId
	}
	return ""
}

type FilterCampaignsReply struct {
	CampaignId           string               `protobuf:"bytes,1,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	InitiatorId          string               `protobuf:"bytes,2,opt,name=initiatorId,proto3" json:"initiatorId,omitempty"`
	OperatorId           string               `protobuf:"bytes,3,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	BeneficiaryId        string               `protobuf:"bytes,4,opt,name=beneficiaryId,proto3" json:"beneficiaryId,omitempty"`
	State                common.CampaignState `protobuf:"varint,5,opt,name=state,proto3,enum=podkrepibg.common.nomenclatures.CampaignState" json:"state,omitempty"`
	CampaignTypes        *CampaignType        `protobuf:"bytes,6,opt,name=campaignTypes,proto3" json:"campaignTypes,omitempty"`
	CampaignSubTypes     *CampaignSubType     `protobuf:"bytes,7,opt,name=campaignSubTypes,proto3" json:"campaignSubTypes,omitempty"`
	Title                string               `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	ShortDescription     string               `protobuf:"bytes,9,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	FullDescription      string               `protobuf:"bytes,10,opt,name=fullDescription,proto3" json:"fullDescription,omitempty"`
	TargetAmount         uint32               `protobuf:"varint,11,opt,name=targetAmount,proto3" json:"targetAmount,omitempty"`
	Currency             common.CurrencyCode  `protobuf:"varint,12,opt,name=currency,proto3,enum=podkrepibg.common.nomenclatures.CurrencyCode" json:"currency,omitempty"`
	RaisedFunds          uint32               `protobuf:"varint,13,opt,name=raisedFunds,proto3" json:"raisedFunds,omitempty"`
	PayedOut             uint32               `protobuf:"varint,14,opt,name=payedOut,proto3" json:"payedOut,omitempty"`
	Donations            []*Donation          `protobuf:"bytes,15,rep,name=donations,proto3" json:"donations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FilterCampaignsReply) Reset()         { *m = FilterCampaignsReply{} }
func (m *FilterCampaignsReply) String() string { return proto.CompactTextString(m) }
func (*FilterCampaignsReply) ProtoMessage()    {}
func (*FilterCampaignsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{7}
}

func (m *FilterCampaignsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterCampaignsReply.Unmarshal(m, b)
}
func (m *FilterCampaignsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterCampaignsReply.Marshal(b, m, deterministic)
}
func (m *FilterCampaignsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterCampaignsReply.Merge(m, src)
}
func (m *FilterCampaignsReply) XXX_Size() int {
	return xxx_messageInfo_FilterCampaignsReply.Size(m)
}
func (m *FilterCampaignsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterCampaignsReply.DiscardUnknown(m)
}

var xxx_messageInfo_FilterCampaignsReply proto.InternalMessageInfo

func (m *FilterCampaignsReply) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *FilterCampaignsReply) GetInitiatorId() string {
	if m != nil {
		return m.InitiatorId
	}
	return ""
}

func (m *FilterCampaignsReply) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *FilterCampaignsReply) GetBeneficiaryId() string {
	if m != nil {
		return m.BeneficiaryId
	}
	return ""
}

func (m *FilterCampaignsReply) GetState() common.CampaignState {
	if m != nil {
		return m.State
	}
	return common.CampaignState_UndefinedCampaign
}

func (m *FilterCampaignsReply) GetCampaignTypes() *CampaignType {
	if m != nil {
		return m.CampaignTypes
	}
	return nil
}

func (m *FilterCampaignsReply) GetCampaignSubTypes() *CampaignSubType {
	if m != nil {
		return m.CampaignSubTypes
	}
	return nil
}

func (m *FilterCampaignsReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FilterCampaignsReply) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *FilterCampaignsReply) GetFullDescription() string {
	if m != nil {
		return m.FullDescription
	}
	return ""
}

func (m *FilterCampaignsReply) GetTargetAmount() uint32 {
	if m != nil {
		return m.TargetAmount
	}
	return 0
}

func (m *FilterCampaignsReply) GetCurrency() common.CurrencyCode {
	if m != nil {
		return m.Currency
	}
	return common.CurrencyCode_UNDEFINED_CURRENCY
}

func (m *FilterCampaignsReply) GetRaisedFunds() uint32 {
	if m != nil {
		return m.RaisedFunds
	}
	return 0
}

func (m *FilterCampaignsReply) GetPayedOut() uint32 {
	if m != nil {
		return m.PayedOut
	}
	return 0
}

func (m *FilterCampaignsReply) GetDonations() []*Donation {
	if m != nil {
		return m.Donations
	}
	return nil
}

type ListCampaignsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCampaignsRequest) Reset()         { *m = ListCampaignsRequest{} }
func (m *ListCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCampaignsRequest) ProtoMessage()    {}
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{8}
}

func (m *ListCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCampaignsRequest.Unmarshal(m, b)
}
func (m *ListCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCampaignsRequest.Marshal(b, m, deterministic)
}
func (m *ListCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCampaignsRequest.Merge(m, src)
}
func (m *ListCampaignsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCampaignsRequest.Size(m)
}
func (m *ListCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCampaignsRequest proto.InternalMessageInfo

type ListCampaignsResponse struct {
	Campaigns            []*CreateCampaignResponse `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListCampaignsResponse) Reset()         { *m = ListCampaignsResponse{} }
func (m *ListCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCampaignsResponse) ProtoMessage()    {}
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{9}
}

func (m *ListCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCampaignsResponse.Unmarshal(m, b)
}
func (m *ListCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCampaignsResponse.Marshal(b, m, deterministic)
}
func (m *ListCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCampaignsResponse.Merge(m, src)
}
func (m *ListCampaignsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCampaignsResponse.Size(m)
}
func (m *ListCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCampaignsResponse proto.InternalMessageInfo

func (m *ListCampaignsResponse) GetCampaigns() []*CreateCampaignResponse {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

type Donation struct {
	DonorDisplayName     string               `protobuf:"bytes,1,opt,name=donorDisplayName,proto3" json:"donorDisplayName,omitempty"`
	Amount               uint32               `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Donation) Reset()         { *m = Donation{} }
func (m *Donation) String() string { return proto.CompactTextString(m) }
func (*Donation) ProtoMessage()    {}
func (*Donation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{10}
}

func (m *Donation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Donation.Unmarshal(m, b)
}
func (m *Donation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Donation.Marshal(b, m, deterministic)
}
func (m *Donation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Donation.Merge(m, src)
}
func (m *Donation) XXX_Size() int {
	return xxx_messageInfo_Donation.Size(m)
}
func (m *Donation) XXX_DiscardUnknown() {
	xxx_messageInfo_Donation.DiscardUnknown(m)
}

var xxx_messageInfo_Donation proto.InternalMessageInfo

func (m *Donation) GetDonorDisplayName() string {
	if m != nil {
		return m.DonorDisplayName
	}
	return ""
}

func (m *Donation) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Donation) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Donation) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateCampaignRequest)(nil), "podkrepibg.campaign.CreateCampaignRequest")
	proto.RegisterType((*CreateCampaignResponse)(nil), "podkrepibg.campaign.CreateCampaignResponse")
	proto.RegisterType((*CampaignTypesRequest)(nil), "podkrepibg.campaign.CampaignTypesRequest")
	proto.RegisterType((*CampaignTypesReply)(nil), "podkrepibg.campaign.CampaignTypesReply")
	proto.RegisterType((*CampaignType)(nil), "podkrepibg.campaign.CampaignType")
	proto.RegisterType((*CampaignSubType)(nil), "podkrepibg.campaign.CampaignSubType")
	proto.RegisterType((*FilterCampaignsRequest)(nil), "podkrepibg.campaign.FilterCampaignsRequest")
	proto.RegisterType((*FilterCampaignsReply)(nil), "podkrepibg.campaign.FilterCampaignsReply")
	proto.RegisterType((*ListCampaignsRequest)(nil), "podkrepibg.campaign.ListCampaignsRequest")
	proto.RegisterType((*ListCampaignsResponse)(nil), "podkrepibg.campaign.ListCampaignsResponse")
	proto.RegisterType((*Donation)(nil), "podkrepibg.campaign.Donation")
}

func init() { proto.RegisterFile("campaign.proto", fileDescriptor_dce769fb84410dc2) }

var fileDescriptor_dce769fb84410dc2 = []byte{
	// 850 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x8e, 0xeb, 0x34,
	0x14, 0x56, 0xfa, 0x77, 0xdb, 0x33, 0xd3, 0x16, 0x7c, 0x7b, 0xab, 0x28, 0x08, 0xe8, 0x8d, 0xae,
	0xa0, 0x77, 0x80, 0x0c, 0x2a, 0x4b, 0x36, 0xc0, 0x94, 0x8b, 0x2a, 0x21, 0x18, 0x65, 0x66, 0x85,
	0xc4, 0xc2, 0x4d, 0xdc, 0x62, 0x91, 0xc4, 0xc1, 0x76, 0x90, 0xf2, 0x1c, 0x6c, 0xd8, 0xb2, 0x60,
	0xc3, 0xe3, 0x20, 0xf1, 0x00, 0xbc, 0x06, 0x2b, 0x14, 0xe7, 0xb7, 0x49, 0x34, 0x29, 0xcc, 0xdd,
	0xc5, 0xdf, 0x39, 0x27, 0xf6, 0xf7, 0x9d, 0x1f, 0x1b, 0x66, 0x0e, 0xf6, 0x43, 0x4c, 0x8f, 0x81,
	0x15, 0x72, 0x26, 0x19, 0x7a, 0x1a, 0x32, 0xf7, 0x47, 0x4e, 0x42, 0xba, 0x3f, 0x5a, 0xb9, 0xc9,
	0x30, 0x1c, 0xe6, 0xfb, 0x2c, 0xb8, 0x0e, 0x98, 0x4f, 0x02, 0xc7, 0xc3, 0x32, 0xe2, 0x44, 0xa4,
	0x01, 0xc6, 0x5b, 0x47, 0xc6, 0x8e, 0x1e, 0xb9, 0x56, 0xab, 0x7d, 0x74, 0xb8, 0x26, 0x7e, 0x28,
	0xe3, 0xcc, 0xf8, 0x6e, 0xdd, 0x28, 0xa9, 0x4f, 0x84, 0xc4, 0x7e, 0x98, 0x3a, 0x98, 0xbf, 0x68,
	0xf0, 0xec, 0x86, 0x13, 0x2c, 0xc9, 0x4d, 0xb6, 0x99, 0x4d, 0x7e, 0x8a, 0x88, 0x90, 0x68, 0x05,
	0x17, 0x34, 0xa0, 0x92, 0x62, 0xc9, 0xf8, 0xce, 0xd5, 0xb5, 0x95, 0xb6, 0x9e, 0xd8, 0x55, 0x08,
	0xbd, 0x03, 0xc0, 0x42, 0xc2, 0x33, 0x87, 0x9e, 0x72, 0xa8, 0x20, 0xe8, 0x05, 0x4c, 0xf7, 0x24,
	0x20, 0x07, 0xea, 0x50, 0xcc, 0xe3, 0x9d, 0xab, 0xf7, 0x95, 0xcb, 0x29, 0x88, 0x10, 0x0c, 0x02,
	0xec, 0x13, 0x7d, 0xa0, 0x8c, 0xea, 0xdb, 0xfc, 0x47, 0x83, 0x65, 0xfd, 0x54, 0x22, 0x64, 0x81,
	0x20, 0xc9, 0xa6, 0xb9, 0x2c, 0xc5, 0xa9, 0x2a, 0x48, 0xf1, 0xbb, 0x5e, 0xf9, 0xbb, 0x3a, 0x95,
	0x7e, 0x17, 0x95, 0x41, 0x37, 0x95, 0x61, 0x1b, 0x95, 0x2d, 0x0c, 0x85, 0xc4, 0x92, 0xe8, 0xa3,
	0x95, 0xb6, 0x9e, 0x6d, 0x2c, 0xab, 0x9a, 0x4b, 0x95, 0x41, 0xeb, 0x34, 0x83, 0x39, 0xbb, 0xbb,
	0x24, 0xca, 0x4e, 0x83, 0xcd, 0x25, 0x2c, 0x72, 0xfc, 0x3e, 0x0e, 0x89, 0xc8, 0x12, 0x62, 0x7e,
	0x0f, 0xa8, 0x86, 0x87, 0x5e, 0x8c, 0xbe, 0x82, 0xa9, 0x53, 0x45, 0x75, 0x6d, 0xd5, 0x5f, 0x5f,
	0x6c, 0x9e, 0x5b, 0x2d, 0x75, 0x64, 0x55, 0xe3, 0xed, 0xd3, 0x38, 0xf3, 0x4f, 0x0d, 0x2e, 0xab,
	0x76, 0xf4, 0x5e, 0x59, 0x9b, 0xc9, 0xba, 0x50, 0xbb, 0x86, 0xa2, 0x2b, 0x78, 0xa3, 0x8a, 0x7c,
	0x53, 0xaa, 0xdf, 0xc0, 0xd1, 0x87, 0xf0, 0x66, 0x15, 0xdb, 0x12, 0xe1, 0xf0, 0x2c, 0x1f, 0x4d,
	0x03, 0xfa, 0x0c, 0xc6, 0x22, 0xda, 0xa7, 0xb4, 0x06, 0x8a, 0xd6, 0x8b, 0x07, 0x69, 0xdd, 0xa5,
	0xce, 0x76, 0x11, 0x65, 0xfe, 0xae, 0xc1, 0xbc, 0x66, 0xad, 0x9e, 0x21, 0x83, 0x0a, 0x6a, 0x4d,
	0x03, 0xfa, 0x18, 0x9e, 0xd6, 0xc0, 0x0a, 0xc1, 0x36, 0x13, 0xda, 0xc0, 0xa2, 0x06, 0x57, 0x69,
	0xb6, 0xda, 0xcc, 0xbf, 0x7b, 0xb0, 0x7c, 0x45, 0x3d, 0x49, 0x78, 0x7e, 0xda, 0x3c, 0xed, 0x6d,
	0x09, 0xd6, 0xfe, 0x4f, 0x82, 0xd1, 0x6d, 0x99, 0xa7, 0xbb, 0x5c, 0xd5, 0x9e, 0xfa, 0xd7, 0x79,
	0xaa, 0x36, 0xa2, 0xcb, 0x7a, 0xef, 0x3f, 0xa2, 0xde, 0x3b, 0x7b, 0xaf, 0xd6, 0xbd, 0xc3, 0x66,
	0xf7, 0x36, 0xba, 0x73, 0xd4, 0xd2, 0x9d, 0xe6, 0x5f, 0x43, 0x58, 0x34, 0x34, 0x4e, 0x5a, 0xa8,
	0x6b, 0xa4, 0xd4, 0x0e, 0xd0, 0xeb, 0x1a, 0x1f, 0xfd, 0xee, 0xf1, 0x31, 0x78, 0x70, 0x7c, 0x0c,
	0x1f, 0x23, 0x67, 0xa3, 0x5e, 0x46, 0xaf, 0xb1, 0x5e, 0x9e, 0x3c, 0xaa, 0x5e, 0x16, 0x30, 0x94,
	0x54, 0x7a, 0x44, 0x1f, 0x2b, 0xfa, 0xe9, 0x22, 0x99, 0x1f, 0xe2, 0x07, 0xc6, 0xa5, 0xea, 0x04,
	0x1a, 0x4a, 0xca, 0x02, 0x7d, 0x92, 0xce, 0x8f, 0x3a, 0x8e, 0xd6, 0x30, 0x3f, 0x44, 0x9e, 0x57,
	0x75, 0x05, 0xe5, 0x5a, 0x87, 0x91, 0x09, 0x97, 0x12, 0xf3, 0x23, 0x91, 0x9f, 0xfb, 0x2c, 0x0a,
	0xa4, 0x7e, 0xb1, 0xd2, 0xd6, 0x53, 0xfb, 0x04, 0x43, 0x3b, 0x18, 0x3b, 0x11, 0xe7, 0x24, 0x70,
	0x62, 0xfd, 0x52, 0x69, 0xfe, 0x51, 0xb7, 0xe6, 0x59, 0xc0, 0x0d, 0x73, 0x89, 0x5d, 0x84, 0x27,
	0x35, 0xc2, 0x31, 0x15, 0xc4, 0x7d, 0x15, 0x05, 0xae, 0xd0, 0xa7, 0x6a, 0xb7, 0x2a, 0x84, 0x0c,
	0x18, 0x87, 0x38, 0x26, 0xee, 0xb7, 0x91, 0xd4, 0x67, 0xca, 0x5c, 0xac, 0xd1, 0xa7, 0x30, 0x71,
	0x59, 0x80, 0x93, 0x83, 0x0b, 0x7d, 0xae, 0x26, 0xdd, 0xdb, 0xad, 0x1a, 0x6f, 0x33, 0x2f, 0xbb,
	0xf4, 0x4f, 0xee, 0x8b, 0xaf, 0xa9, 0x90, 0xf5, 0xc1, 0x61, 0xee, 0xe1, 0x59, 0x0d, 0xcf, 0xae,
	0xd0, 0x1d, 0x4c, 0xf2, 0x1f, 0xe6, 0xd7, 0xc5, 0x07, 0xed, 0x19, 0x6d, 0xbd, 0x82, 0xed, 0x32,
	0xda, 0xfc, 0x55, 0x83, 0x71, 0x7e, 0xa6, 0x24, 0x91, 0x2e, 0x0b, 0x18, 0xdf, 0x52, 0x11, 0x7a,
	0x38, 0x56, 0x73, 0x32, 0xed, 0xa6, 0x06, 0x8e, 0x96, 0x30, 0xc2, 0x69, 0x62, 0x7a, 0x4a, 0x8b,
	0x6c, 0x85, 0x74, 0x78, 0xe2, 0x13, 0x21, 0xf0, 0x91, 0x64, 0x6d, 0x94, 0x2f, 0x91, 0x05, 0x03,
	0x37, 0x69, 0x8e, 0x81, 0x2a, 0x41, 0xc3, 0x4a, 0x5f, 0x36, 0x56, 0xfe, 0xb2, 0xb1, 0xee, 0xf3,
	0x97, 0x8d, 0xad, 0xfc, 0x36, 0xbf, 0xf5, 0x2b, 0xa3, 0x9f, 0xf0, 0x9f, 0xa9, 0x43, 0x10, 0x85,
	0xd9, 0x29, 0x27, 0x74, 0x75, 0x16, 0x71, 0x25, 0xa8, 0xf1, 0x5f, 0x44, 0x42, 0x07, 0x98, 0x9e,
	0xa8, 0x8f, 0x5e, 0xb6, 0x46, 0xb7, 0x65, 0xce, 0xb8, 0x3a, 0xc7, 0x35, 0xdb, 0xe7, 0x16, 0xa6,
	0x27, 0xaf, 0x02, 0xb4, 0x6c, 0x28, 0xf3, 0x65, 0xf2, 0x20, 0x34, 0xde, 0xef, 0x1c, 0x00, 0xd9,
	0x38, 0xa4, 0x30, 0xaf, 0x8d, 0x49, 0xd4, 0xce, 0xbc, 0xfd, 0xc2, 0x32, 0x5e, 0x9e, 0xe7, 0x1c,
	0x7a, 0xf1, 0x17, 0xcf, 0xbf, 0x1b, 0xe7, 0x0e, 0x7f, 0xf4, 0x16, 0xb7, 0x65, 0x58, 0xe1, 0xb7,
	0x1f, 0x29, 0x1a, 0x9f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xf9, 0x8f, 0xad, 0x28, 0x0b,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampaignServiceClient is the client API for CampaignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampaignServiceClient interface {
	// creates a new campaign
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error)
	// list campaign
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error)
	CampaignTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CampaignTypesReply, error)
	FilterCampaigns(ctx context.Context, in *FilterCampaignsRequest, opts ...grpc.CallOption) (*FilterCampaignsReply, error)
}

type campaignServiceClient struct {
	cc *grpc.ClientConn
}

func NewCampaignServiceClient(cc *grpc.ClientConn) CampaignServiceClient {
	return &campaignServiceClient{cc}
}

func (c *campaignServiceClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error) {
	out := new(CreateCampaignResponse)
	err := c.cc.Invoke(ctx, "/podkrepibg.campaign.CampaignService/CreateCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error) {
	out := new(ListCampaignsResponse)
	err := c.cc.Invoke(ctx, "/podkrepibg.campaign.CampaignService/ListCampaigns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CampaignTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CampaignTypesReply, error) {
	out := new(CampaignTypesReply)
	err := c.cc.Invoke(ctx, "/podkrepibg.campaign.CampaignService/CampaignTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) FilterCampaigns(ctx context.Context, in *FilterCampaignsRequest, opts ...grpc.CallOption) (*FilterCampaignsReply, error) {
	out := new(FilterCampaignsReply)
	err := c.cc.Invoke(ctx, "/podkrepibg.campaign.CampaignService/FilterCampaigns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignServiceServer is the server API for CampaignService service.
type CampaignServiceServer interface {
	// creates a new campaign
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error)
	// list campaign
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	CampaignTypes(context.Context, *empty.Empty) (*CampaignTypesReply, error)
	FilterCampaigns(context.Context, *FilterCampaignsRequest) (*FilterCampaignsReply, error)
}

// UnimplementedCampaignServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCampaignServiceServer struct {
}

func (*UnimplementedCampaignServiceServer) CreateCampaign(ctx context.Context, req *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (*UnimplementedCampaignServiceServer) ListCampaigns(ctx context.Context, req *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (*UnimplementedCampaignServiceServer) CampaignTypes(ctx context.Context, req *empty.Empty) (*CampaignTypesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CampaignTypes not implemented")
}
func (*UnimplementedCampaignServiceServer) FilterCampaigns(ctx context.Context, req *FilterCampaignsRequest) (*FilterCampaignsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterCampaigns not implemented")
}

func RegisterCampaignServiceServer(s *grpc.Server, srv CampaignServiceServer) {
	s.RegisterService(&_CampaignService_serviceDesc, srv)
}

func _CampaignService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podkrepibg.campaign.CampaignService/CreateCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podkrepibg.campaign.CampaignService/ListCampaigns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CampaignTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CampaignTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podkrepibg.campaign.CampaignService/CampaignTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CampaignTypes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_FilterCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).FilterCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podkrepibg.campaign.CampaignService/FilterCampaigns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).FilterCampaigns(ctx, req.(*FilterCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CampaignService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podkrepibg.campaign.CampaignService",
	HandlerType: (*CampaignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _CampaignService_CreateCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _CampaignService_ListCampaigns_Handler,
		},
		{
			MethodName: "CampaignTypes",
			Handler:    _CampaignService_CampaignTypes_Handler,
		},
		{
			MethodName: "FilterCampaigns",
			Handler:    _CampaignService_FilterCampaigns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaign.proto",
}
