name: Check PR

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests
    if: |
      !github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]'
    uses: ./.github/workflows/tests.yml
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
      MONDOO_SECRET: ${{ secrets.MONDOO_SECRET }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}