name: Tests

on:
  workflow_call:

jobs:
  build-frontend:
    name: Build and scan frontend container image
    uses: ./.github/workflows/build-frontend-docker.yml
    with:
      environment: test
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  build-maintenance:
    name: Build and scan maintenance container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build
        uses: docker/build-push-action@v7
        with:
          push: false
          file: Dockerfile.maintenance
          tags: ghcr.io/podkrepi-bg/maintenance:pr

      - name: Scan with Mondoo
        uses: mondoohq/actions/docker-image@main
        env:
          MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SECRET }}
        with:
          image: ghcr.io/podkrepi-bg/maintenance:pr

  scan-manifests:
   name: Scan k8s manifests
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v6
       with:
         ref: ${{ github.event.pull_request.head.sha }}

     - name: Install kustomize
       uses: imranismail/setup-kustomize@v3

     - name: Build development manifests
       run: kustomize build manifests/overlays/development > dev-manifests.yaml

     - name: Scan development manifests with Mondoo
       uses: mondoohq/actions/k8s-manifest@main
       env:
         MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SECRET }}
       with:
         path: dev-manifests.yaml

     - name: Build production manifests
       run: kustomize build manifests/overlays/production > prod-manifests.yaml

     - name: Scan production manifests with Mondoo
       uses: mondoohq/actions/k8s-manifest@main
       env:
         MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_SECRET }}
       with:
         path: prod-manifests.yaml

  run-playwright:
    name: Run Playwright
    uses: ./.github/workflows/playwright.yml
    secrets: inherit
